
package pckcentiscapews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentiscapeWS", targetNamespace = "http://pckCentiscapeWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CentiscapeWS {


    /**
     * 
     * @param lngCentralities
     * @param pUser
     * @return
     *     returns long
     */
    @WebMethod(operationName = "Request")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Request", targetNamespace = "http://pckCentiscapeWS/", className = "pckcentiscapews.Request")
    @ResponseWrapper(localName = "RequestResponse", targetNamespace = "http://pckCentiscapeWS/", className = "pckcentiscapews.RequestResponse")
    @Action(input = "http://pckCentiscapeWS/CentiscapeWS/RequestRequest", output = "http://pckCentiscapeWS/CentiscapeWS/RequestResponse")
    public long request(
        @WebParam(name = "pUser", targetNamespace = "")
        byte[] pUser,
        @WebParam(name = "lngCentralities", targetNamespace = "")
        long lngCentralities);

    /**
     * 
     * @param intStreamLength
     * @param pNetworkStream
     * @param lngIdRequest
     * @param pNetworkName
     * @param pUser
     * @return
     *     returns long
     */
    @WebMethod(operationName = "LoadNetwork")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LoadNetwork", targetNamespace = "http://pckCentiscapeWS/", className = "pckcentiscapews.LoadNetwork")
    @ResponseWrapper(localName = "LoadNetworkResponse", targetNamespace = "http://pckCentiscapeWS/", className = "pckcentiscapews.LoadNetworkResponse")
    @Action(input = "http://pckCentiscapeWS/CentiscapeWS/LoadNetworkRequest", output = "http://pckCentiscapeWS/CentiscapeWS/LoadNetworkResponse")
    public long loadNetwork(
        @WebParam(name = "lngIdRequest", targetNamespace = "")
        long lngIdRequest,
        @WebParam(name = "pUser", targetNamespace = "")
        byte[] pUser,
        @WebParam(name = "pNetworkName", targetNamespace = "")
        byte[] pNetworkName,
        @WebParam(name = "pNetworkStream", targetNamespace = "")
        byte[] pNetworkStream,
        @WebParam(name = "intStreamLength", targetNamespace = "")
        int intStreamLength);

}
