
package pckcentiscapews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentiscapeWS", targetNamespace = "http://pckCentiscapeWS/", wsdlLocation = "http://157.27.10.103:8080/CentiscapeWS/CentiscapeWS?wsdl")
public class CentiscapeWS_Service
    extends Service
{

    private final static URL CENTISCAPEWS_WSDL_LOCATION;
    private final static WebServiceException CENTISCAPEWS_EXCEPTION;
    private final static QName CENTISCAPEWS_QNAME = new QName("http://pckCentiscapeWS/", "CentiscapeWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://157.27.10.103:8080/CentiscapeWS/CentiscapeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTISCAPEWS_WSDL_LOCATION = url;
        CENTISCAPEWS_EXCEPTION = e;
    }

    public CentiscapeWS_Service() {
        super(__getWsdlLocation(), CENTISCAPEWS_QNAME);
    }

    public CentiscapeWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTISCAPEWS_QNAME, features);
    }

    public CentiscapeWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CENTISCAPEWS_QNAME);
    }

    public CentiscapeWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTISCAPEWS_QNAME, features);
    }

    public CentiscapeWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentiscapeWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentiscapeWS
     */
    @WebEndpoint(name = "CentiscapeWSPort")
    public CentiscapeWS getCentiscapeWSPort() {
        return super.getPort(new QName("http://pckCentiscapeWS/", "CentiscapeWSPort"), CentiscapeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentiscapeWS
     */
    @WebEndpoint(name = "CentiscapeWSPort")
    public CentiscapeWS getCentiscapeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pckCentiscapeWS/", "CentiscapeWSPort"), CentiscapeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTISCAPEWS_EXCEPTION!= null) {
            throw CENTISCAPEWS_EXCEPTION;
        }
        return CENTISCAPEWS_WSDL_LOCATION;
    }

}
