/*
 * CentiScaPeHelp.java
 *
 * Created on 18 gennaio 2008, 12.30
 */
package org.cytoscape.centiscape.internal;

/**
 *
 * @author scardoni
 */
public class CentiScaPeHelp extends javax.swing.JFrame {

    private String helpString;

    /**
     * Creates new form CentiScaPeHelp
     */
    public CentiScaPeHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE).addContainerGap()));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CentiScaPeHelp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void setText(int centrality) {
        switch (centrality) {
            case 0: {
                helpString =
                        "DIAMETER: description\n\n"
                        + "The diameter is the maximal distance (shortest path) amongst all the distances\n"
                        + "calculated between each couple of vertexes in graph.\n"
                        + "The diameter indicates how much distant are the two most distant nodes. It\n"
                        + "can be a first and simple general parameter of graph \"compactness\", meaning\n"
                        + "with that the overall proximity between nodes. A \"high\" graph diameter\n"
                        + "indicates that the two nodes determining that diameter are very distant,\n"
                        + "implying little graph compactness. However, it is possible that two nodes\n"
                        + "are very distant, thus giving a high graph diameter, but several other nodes\n"
                        + "are not. Therefore, a graph could have high diameter and still being rather\n"
                        + "compact or have very compact regions. Thus, a high graph diameter can be\n"
                        + "misleading in term of evaluation of graph compactness. In contrast a \"low\" \n"
                        + "graph diameter is much more informative and reliable. Indeed, a low diameter\n"
                        + "surely indicates that all the nodes are in proximity and the graph is\n"
                        + "compact. In quantitative terms, \"high\" and \"low\" are better defined when\n"
                        + "compared to the total number of nodes in the graph. Thus, a low diameter of\n"
                        + "a very big graph (with hundreds of nodes) is much more meaningful in term of\n"
                        + "compactness than a low diameter of a small graph (with few nodes). Notably,\n"
                        + "the diameter enables to measure the development of a network in time.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe diameter, and thus the compactness, of a biological\n"
                        + "network, for instance a protein-signaling network, can be interpreted as the\n"
                        + "overall easiness of the proteins to communicate and/or influence their\n"
                        + "reciprocal function. It could be also a sign of functional convergence.\n"
                        + "Indeed, a big protein network with low diameter may suggest that the\n"
                        + "proteins within the network had a functional co-evolution. The diameter\n"
                        + "should be carefully weighted if the graph is not fully connected (that is,\n"
                        + "there are isolated nodes).\n";
                this.setTitle("CentiScaPe Help: Diameter ");
            }
            break;
            case 1: {
                helpString =
                        "AVERAGE DISTANCE: description\n\n"
                        + "The average distance is the average shortest path of a graph, corresponding\n"
                        + "to the summa of all shortest paths between vertex couples divided for the\n"
                        + "total number of vertex couples. Often it is not an integer.\n"
                        + "As for the diameter, it can be a simple and general parameter of graph\n"
                        + "\"compactness\", meaning with that the overall tendency of nodes to stay in\n"
                        + "proximity. Being an average, it can be somehow more informative than the\n"
                        + "diameter and can be also considered a general indicator of network\n"
                        + "\"navigability\". A \"high\" average distance indicates that the nodes are\n"
                        + "distant (disperse), implying little graph compactness. In contrast a \"low\"\n"
                        + "average distance indicates that all the nodes are in proximity and the graph\n"
                        + "is compact. In quantitative terms, \"high\" and \"low\" are better defined when\n"
                        + "compared to the total number of nodes in the graph. Thus, a low average\n"
                        + "distance of a very big graph (with hundreds of nodes) is more meaningful in\n"
                        + "term of compactness than a low average distance of a small graph (with few\n"
                        + "nodes).\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe average distance of a biological network, for\n"
                        + "instance a protein-signaling network, can be interpreted as the overall\n"
                        + "easiness of the proteins to communicate and/or influence their reciprocal\n"
                        + "function. It could be also a sign of functional convergence. Indeed, a big\n"
                        + "protein network with low average distance may suggest that the proteins\n"
                        + "within the network have the tendency to generate functional complexes and/or\n"
                        + "modules (although centrality indexes should be also calculated to support\n"
                        + "that indication).";
                this.setTitle("CentiScaPe Help: Average distance ");
            }
            break;
            case 2: {
                helpString =
                        "DEGREE: description \n\n"
                        + "The degree is the simplest topological index, corresponding to the number of nodes\n"
                        + "adjacent to a given node v, where \"adjacent\" means directly connected. The\n"
                        + "nodes directly connected to a given node v are also called \"first neighbors\"\n"
                        + "of the given node. Thus, the degree also corresponds to the number of\n"
                        + "adjacent incident edges. In directed networks we distinguish in-degree, when\n"
                        + "the edges target the node v, and out-degree, when the edges target the\n"
                        + "adjacent neighbors of v.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe degree allows an immediate evaluation of the\n"
                        + "regulatory relevance of the node. For instance, in signaling networks,\n"
                        + "proteins with very high degree are interacting with several other signaling\n"
                        + "proteins, thus suggesting a central regulatory role, that is they are likely\n"
                        + "to be regulatory \"hubs\". For instance, signaling proteins encoded by\n"
                        + "oncogenes, such as HRAS, SRC or TP53, are hubs. Depending on the nature of\n"
                        + "the protein, the degree could indicate a central role in amplification\n"
                        + "(kinases), diversification and turnover (small GTPases), signaling module\n"
                        + "assembly (docking proteins), gene expression (transcription factors), etc.\n"
                        + "Signaling networks have typically a scale-free architecture.\n";
                this.setTitle("CentiScaPe Help: Node Degree ");
            }
            break;
            case 3: {
                helpString =
                        "ECCENTRICITY: description\n\n"
                        + "The eccentricity is a node centrality index. The eccentricity of a node v is\n"
                        + "calculated by computing the shortest path between the node v and all other\n"
                        + "nodes in the graph, then the \"longest\" shortest path is chosen (let (v, K)\n"
                        + "where K is the most distance node from v). Once this path with length\n"
                        + "dist(v, K) is identified, its reciprocal is calculated (1/dist(v, K)). By\n"
                        + "doing that, an eccentricity with higher value assumes a positive meaning in\n"
                        + "term of node proximity. Indeed, if the eccentricity of the node v is high,\n"
                        + "this means that all other nodes are in proximity. In contrast, if the\n"
                        + "eccentricity is low, this means that there is at least one node (and all its\n"
                        + "neighbors) that is far form node v. Of course, this does not exclude that\n"
                        + "several other nodes are much closer to node v. Thus, eccentricity is a more\n"
                        + "meaningful parameter if is high. Notably, \"high\" and \"low\" values are more\n"
                        + "significant when compared to the average eccentricity of the graph G\n"
                        + "calculated by averaging the eccentricity values of all nodes in the graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe eccentricity of a node in a biological network, for\n"
                        + "instance a protein-signaling network, can be interpreted as the easiness of\n"
                        + "a protein to be functionally reached by all other proteins in the network.\n"
                        + "Thus, a protein with high eccentricity, compared to the average eccentricity\n"
                        + "of the network, will be more easily influenced by the activity of other\n"
                        + "proteins (the protein is subject to a more stringent or complex regulation)\n"
                        + "or, conversely could easily influence several other proteins. In contrast, a\n"
                        + "low eccentricity, compared to the average eccentricity of the network, could\n"
                        + "indicate a marginal functional role (although this should be also evaluated\n"
                        + "with other parameters and contextualized to the network annotations).\n";
                this.setTitle("CentiScaPe Help: Eccentricity ");
            }
            break;
            case 4: {
                helpString =
                        "RADIALITY: description\n\n"
                        + "The radiality is a node centrality index. The radiality of a node v is\n"
                        + "calculated by computing the shortest path between the node v and all other\n"
                        + "nodes in the graph. The value of each path is then subtracted by the value\n"
                        + "of the diameter + 1 and the resulting values are summated. Finally,\n"
                        + "the obtained value is divided for the number of nodes -1 (n-1). Basically,\n"
                        + "as the diameter is the maximal possible distance between nodes, subtracting\n"
                        + "systematically from the diameter the shortest paths between the node v and\n"
                        + "its neighbors will give high values if the paths are short and low values if\n"
                        + "the paths are long. Overall, if the radiality is high this means that, with\n"
                        + "respect to the diameter, the node is generally closer to the other nodes,\n"
                        + "whereas, if the radiality is low, this means that the node is peripheral.\n"
                        + "Also here, \"high\" and \"low\" values are more meaningful when compared to the\n"
                        + "average radiality of the graph G calculated by averaging the radiality\n"
                        + "values of all nodes in the graph.\n"
                        + "As for the closeness, the radiality value should be considered as an\n"
                        + "\"average tendency to node proximity or isolation\", not definitively\n"
                        + "informative on the centrality of the individual node. The radiality should\n"
                        + "be always compared to the closeness and to the eccentricity: a node with\n"
                        + "high eccentricity + high closeness+ high radiality is a consistent\n"
                        + "indication of a high central position in the graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe radiality of a node in a biological network, for\n"
                        + "instance a protein-signaling network, can be interpreted as the\n"
                        + "\"probability\" of a protein to be functionally relevant for several other\n"
                        + "proteins, but with the possibility to be irrelevant for few other proteins.\n"
                        + "Thus, a protein with high radiality, compared to the average radiality of\n"
                        + "the network, will be easily central to the regulation of other proteins but\n"
                        + "with some proteins not influenced by its activity.  Notably, in biological\n"
                        + "networks could be also of interest to analyze proteins with low radiality,\n"
                        + "compared to the average radiality of the network, as these proteins,\n"
                        + "although less relevant for that specific network, are possibly behaving as\n"
                        + "intersecting boundaries with other networks. Accordingly, a signaling\n"
                        + "network with a very high average radiality is more likely organizing\n"
                        + "functional units or modules, whereas a signaling network with very low\n"
                        + "average radiality will behave more likely as an open cluster of proteins\n"
                        + "connecting different regulatory modules. All these interpretations should be\n"
                        + "accompanied to the contemporary evaluation of eccentricity and closeness.\n";
                this.setTitle("CentiScaPe Help: Radiality");
            }
            break;
            case 5: {
                helpString =
                        "CLOSENESS: description\n\n"
                        + "The closeness is a node centrality index. The closeness of a node v is\n"
                        + "calculated by computing the shortest path between the node v and all other\n"
                        + "nodes in the graph, and then calculating the summa. Once this value is\n"
                        + "obtained, its reciprocal is calculated, so higher values assume a positive\n"
                        + "meaning in term of node proximity. Also here, \"high\" and \"low\" values are\n"
                        + "more meaningful when compared to the average closeness of the graph G\n"
                        + "calculated by averaging the closeness values of all nodes in the graph.\n"
                        + "Notably, high values of closeness should indicate that all other nodes are\n"
                        + "in proximity to node v. In contrast, low values of closeness should indicate\n"
                        + "that all other nodes are distant from node v. However, a high closeness\n"
                        + "value can be determined by the presence of few nodes very close to node v,\n"
                        + "with other much more distant, or by the fact that all nodes are generally\n"
                        + "very close to v. Likewise, a low closeness value can be determined by the\n"
                        + "presence of few nodes very distant from node v, with other much closer, or\n"
                        + "by the fact that all nodes are generally distant from v. Thus, the closeness\n"
                        + "value should be considered as an \"average tendency to node proximity or\n"
                        + "isolation\", not really informative on the specific nature of the individual\n"
                        + "node couples. The closeness should be always compared to the eccentricity: a\n"
                        + "node with high eccentricity + high closeness is very likely to be central in\n"
                        + "the graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe closeness of a node in a biological network, for\n"
                        + "instance a protein-signaling network, can be interpreted as the\n"
                        + "\"probability\" of a protein to be functionally relevant for several other\n"
                        + "proteins, but with the possibility to be irrelevant for few other proteins.\n"
                        + "Thus, a protein with high closeness, compared to the average closeness of\n"
                        + "the network, will be easily central to the regulation of other proteins but\n"
                        + "with some proteins not influenced by its activity.  Notably, in biological\n"
                        + "networks could be also of interest to analyze proteins with low closeness,\n"
                        + "compared to the average closeness of the network, as these proteins,\n"
                        + "although less relevant for that specific network, are possibly behaving as\n"
                        + "intersecting boundaries with other networks. Accordingly, a signaling\n"
                        + "network with a very high average closeness is more likely organizing\n"
                        + "functional units or modules, whereas a signaling network with very low\n"
                        + "average closeness will behave more likely as an open cluster of proteins\n"
                        + "connecting different regulatory modules.\n";
                this.setTitle("CentiScaPe Help: Closeness");
            }
            break;
            case 6: {
                helpString =
                        "STRESS: description\n\n"
                        + "The stress is a node centrality index. Stress is calculated by measuring the\n"
                        + "number of shortest paths passing through a node. To calculate the \"stress\"\n"
                        + "of a node v, all shortest paths in a graph G are calculated and then the\n"
                        + "number of shortest paths passing through v is counted. A \"stressed\" node is\n"
                        + "a node traversed by a high number of shortest paths. Notably, and\n"
                        + "importantly, a high stress values does not automatically implies that the\n"
                        + "node v is critical to maintain the connection between nodes whose paths are\n"
                        + "passing through it. Indeed, it is possible that two nodes are connected by\n"
                        + "means of other shortest paths not passing through the node v. Also here,\n"
                        + "\"high\" and \"low\" values are more meaningful when compared to the average\n"
                        + "stress value of the graph G calculated by averaging the stress values of all\n"
                        + "nodes in the graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe stress of a node in a biological network, for\n"
                        + "instance a protein-signaling network, can indicate the relevance of a\n"
                        + "protein as functionally capable of holding together communicating nodes. The\n"
                        + "higher the value the higher the relevance of the protein in connecting\n"
                        + "regulatory molecules. Due to the nature of this centrality, it is possible\n"
                        + "that the stress simply indicates a molecule heavily involved in cellular\n"
                        + "processes but not relevant to maintain the communication between other\n"
                        + "proteins.";
                this.setTitle("CentiScaPe Help: Stress");
            }
            break;
            case 7: {
                helpString =
                        "BETWEENNESS: description\n\n"
                        + "The S.-P. Betweenness is a node centrality index. It is similar to the\n"
                        + "stress but provides a more elaborated and informative centrality index. It\n"
                        + "is calculated considering couples of nodes (v1, v2) and counting the number\n"
                        + "of shortest paths linking v1 and v2 and passing through a node n. Then, the\n"
                        + "value is related to the total number of shortest paths linking v1 and v2.\n"
                        + "Thus, a node can be traversed by only one path linking v1 and v2, but if\n"
                        + "this path is the only connecting v1 and v2 the node n will score a higher\n"
                        + "betweenness value (in the stress computation would have had a low score).\n"
                        + "Thus, a high S.-P. Betweenness score means that the node, for certain paths,\n"
                        + "is crucial to maintain node connections. Notably, to know the number of\n"
                        + "paths for which the node is critical it is necessary to look at the stress.\n"
                        + "Thus, stress and S.-P. Betweenness can be used to gain complementary\n"
                        + "information. Further information could be gained by referring the S.-P.\n"
                        + "Betweenness to node couples, thus \"quantifying\" the importance of a node for\n"
                        + "two connected nodes. Also here, \"high\" and \"low\" values are more meaningful\n"
                        + "when compared to the average S.-P. Betweenness value of the graph G\n"
                        + "calculated by averaging the S.-P. Betweenness values of all nodes in the\n"
                        + "graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe S.-P. Betweenness of a node in a biological\n"
                        + "network, for instance a protein-signaling network, can indicate the\n"
                        + "relevance of a protein as functionally capable of holding together\n"
                        + "communicating proteins. The higher the value the higher the relevance of the\n"
                        + "protein as organizing regulatory molecule. The S.-P. Betweenness of a\n"
                        + "protein effectively indicates the capability of a protein to bring in\n"
                        + "communication distant proteins. In signaling modules, proteins with high\n"
                        + "S.-P. Betweenness are likely crucial to maintain functionally and coherence\n"
                        + "of signaling mechanisms.";
                this.setTitle("CentiScaPe Help: Betweenness");
            }
            break;
            case 8: {
                helpString =
                        "CENTROID VALUE: description\n\n"
                        + "The centroid value is the most complex node centrality index. It is computed\n"
                        + "by focusing the calculus on couples of nodes (v, w) and systematically\n"
                        + "counting the nodes that are closer (in term of shortest path) to v or to w.\n"
                        + "The calculus proceeds by comparing the node distance from other nodes with\n"
                        + "the distance of all other nodes from the others, such that a high centroid\n"
                        + "value indicates that a node v is much closer to other nodes. Thus, the\n"
                        + "centroid value provides a centrality index always weighted with the values\n"
                        + "of all other nodes in the graph. Indeed, the node with the highest centroid\n"
                        + "value is also the node with the highest number of neighbors (not only first)\n"
                        + "if compared with all other nodes. In other terms, a node v with the highest\n"
                        + "centroid value is the node with the highest number of neighbors separated by\n"
                        + "the shortest path to v. The centroid value suggests that a specific node has\n"
                        + "a central position within a graph region characterized by a high density of\n"
                        + "interacting nodes. Also here, \"high\" and \"low\" values are more meaningful\n"
                        + "when compared to the average centrality value of the graph G calculated by\n"
                        + "averaging the centrality values of all nodes in the graph.\n\n"
                        + "IN BIOLOGICAL TERMS\n\nThe centrality value of a node in a biological network,\n"
                        + "for instance a protein-signaling network, can be interpreted as the\n"
                        + "\"probability\" of a protein to be functionally capable of organizing discrete\n"
                        + "protein clusters or modules. Thus, a protein with high centroid value,\n"
                        + "compared to the average centroid value of the network, will be possibly\n"
                        + "involved in coordinating the activity of other highly connected proteins,\n"
                        + "altogether devoted to the regulation of a specific cell activity (for\n"
                        + "instance, cell adhesion, gene expression, proliferation etc.). Accordingly,\n"
                        + "a signaling network with a very high average centroid value is more likely\n"
                        + "organizing functional units or modules, whereas a signaling network with\n"
                        + "very low average centroid value will behave more likely as an open cluster\n"
                        + "of proteins connecting different regulatory modules. It can be useful to\n"
                        + "compare the centroid value to other algorithms detecting dense regions in a\n"
                        + "graph, indicating protein clusters, such as, for instance, MCODE.";
                this.setTitle("CentiScaPe Help: Centroid value");
            }
            break;
            case 9: {
                helpString =
                        "EIGENVECTOR CENTRALITY: Description\n\nDefinition:\n"
                        + "The Eigenvector centrality is a node centrality index. It assigns relative \n"
                        + "scores to all nodes in the network based on the concept that connections to \n"
                        + "high-scoring nodes contribute more to the score of the node in question than \n"
                        + "equal connections to low-scoring nodes. Calculating Eigenvector centrality \n"
                        + "is an iterative process. Eigenvector Centrality is calculated using adjacency \n"
                        + "matrix of the graph. Eigen vector of the principle Eigen value or the largest \n"
                        + "Eigen value gives us Eigenvector centrality for each of the nodes.\n\n"
                        + "USEFULNESS:\n\n"
                        + "Eigenvector centrality crops up in vast array of fields Huge area in which\n"
                        + "Eigenvector centrality is used is to determine rank of a node in a network.\n"
                        + "A more well-known application comes from something very familiar to almost all\n"
                        + "of us: Google. Google’s Page Rank is a system by which the search engine ranks\n"
                        + "the pages in its search results. Page Rank for a node is calculated recursively\n"
                        + "by calling the Page Rank of its connected nodes and so does Eigenvector. Obviously,\n"
                        + "there was greater sophistication necessary in the basic model of Eigenvector for\n"
                        + "calculating Page Rank because of the internet being so vast. A High Eigenvector\n"
                        + "centrality indicates that the node is being visited a lot while traversing and is\n"
                        + "well-connected.\n";
                this.setTitle("CentiScaPe Help: EigenVector Centrality");
            }
            break;
            case 10: {
                helpString = "BRIDGING CENTRALITY: Description\n\n"
                        + "The bridging centrality of a node is the product of the betweenness centrality CB\n"
                        + "and the bridging coefficient (BC), which measures the global and local features of\n"
                        + "a node, respectively. The bridging coefficient of a node determines the extent how\n"
                        + "well the node is located between high degree nodes. The bridging coefficient of a\n"
                        + "node v is defined as the inverse of degree of that node divided by sum of inverses\n"
                        + "of all the degrees of its neighboring nodes. Higher Bridging centrality signifies\n"
                        + "that more information flows through that node.\n"
                        + "IN BIOLOGICAL TERMS\n\n"
                        + "The yeast metabolic network is relatively well modularized and clustered according\n"
                        + "to their cellular functions. From a visual inspection by using CentiScaPe, it shows\n"
                        + "that bridging centrality successfully identifies the bridging nodes and the nodes\n"
                        + "lying on the borders of modules. Importantly, the majority of its key bridging nodes\n"
                        + "can be readily identified by visual inspection.";
                this.setTitle("CentiScaPe Help: Bridging Centrality");
            }
            break;
            case 11: {
                helpString = "EDGE BETWEENNESS CENTRALITY: Description\n\n"
                        + "The edge gives us the amount of flow through an edge. Edge betweenness of an edge is\n"
                        + "the number of shortest paths between pairs of nodes that run along it. If there is\n"
                        + "more than one shortest path between a pair of nodes, each path is assigned equal weight\n"
                        + "such that the total weight of all of the paths is equal to unity. Thus, the edges\n"
                        + "connecting two networks will have high edge betweenness value.\n\n"
                        + "After the calculation, Edge betweenness values can be found in edge table of the network.";
                this.setTitle("CentiScaPe Help: Edge Betweenness Centrality");
            }
            break;
        }
        jTextArea1.setText(helpString);
        jTextArea1.setCaretPosition(0);
    }
}
